version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres_testbot
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: doniyor2007
      POSTGRES_DB: medicin_test_bot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test-bot:
    build: .
    container_name: test-bot
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/medicin_test_bot
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: doniyor2007

volumes:
  postgres_data:
